### ISSUE TITLE
Update description

### ISSUE THREAD

**Issue by MahanRahmati** [leanflutter/awesome-flutter-desktop#20]
How can I update description of my repository?
I want to change it to:
- [arna](https://github.com/MahanRahmati/Arna) - A set of widgets designed to be simple and easy to use for building applications with Flutter. ([Live Preview](https://mahanrahmati.github.io/arna_demo/))

**Comment by lijy91** [comment]
This description is from the description of pub, if you update the description in pubspec.yaml and republish it, I will update it

**Comment by MahanRahmati** [comment]
Thanks!🙏
