### ISSUE TITLE
[question] Should we separate plugins & packages in the README?

### ISSUE THREAD

**Issue by alexmercerind** [leanflutter/awesome-flutter-desktop#8]
Currently both plugins & packages are mentioned under same "Package" sub-heading.

It will be more easier to browse for the visitors, if plugins (_exposing some native OS functionality to Dart (or Flutter) / containing native code / making native OS method calls / exposing any other third party non-Dart library (C/C++, obj-C, Rust or Go?) to Dart (or Flutter) / FFI bindings_) & package (_Flutter widgets implementing "native" design or decorations / other Dart-only utilities_) are mentioned under separate headings.

Just an opinion, I thought in future number of packages/plugins/apps is definitely going to increase, so list may end up cluttered.

**Comment by lijy91** [comment]
I think we should add categories to package/plugin, like as
UI, Media, Storage, Utils or more.

Make it look like this:

## Packages

### UI
- PKGA
- PKGB
### Media
- PKGC
- PKGD
### Storage
- PKGE
- PKGF
### Utils
- PKGG
- PKGH

I will add these later

**Comment by jpnurmi** [comment]
Separate sections for platform-specific packages (dbus, win32, ...) could also work, but the more sections you have the harder it gets to choose between overlapping sections. Alternatively, platform-specific packages could be marked with badges.

**Comment by alexmercerind** [comment]
Closing. Thanks for consideration!
